name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-test:
    uses: ./.github/workflows/unit_test.yml

  build-test:
    needs: unit-test
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}